### ISSUE TITLE
Demande serveur AWS 

### ISSUE THREAD

**Issue by SebastienMoraz** [CPNV-PRETPI/MORAZ-SEBASTIEN#1]
Bonjour @NicolasGlassey,

Voici la description des config serveur que j'aurai besoin:

- Ubuntu Server
- Apache 2.4
- MariaDB
- PHP 8.2.2

merci, bonne journée a vous.

Sébastien Moraz

**Comment by NicolasGlassey** [comment]
@SebastienMoraz 

Voici les informations concernant l'instance demandée:

https://github.com/CPNV-PRETPI/MORAZ-SEBASTIEN/wiki/Environnement-d'int%C3%A9gration

**Comment by NicolasGlassey** [comment]
@SebastienMoraz 

Pour pouvoir gérer votre instance, voici la documenation

https://github.com/CPNV-PRETPI/MORAZ-SEBASTIEN/wiki/Environnement-d'int%C3%A9gration#sla

Votre instance id est : i-0fd051eb4a1233c6d
